# Uso de cada token, escrito no presente: o que ele É e onde entra.
# Sem histórico, sem medida no texto (a medida é calculada e mostrada na pastilha).
USO = {
 # Marca / Interativo
 'Background/Brand': 'Preenchimento de marca: botão primário, chip selecionado, trilho ativo. Em cima dele vai Content/OnFill.',
 'Content/Brand': 'Texto, ícone e link de marca sobre fundo claro neutro. Sobre fundo claro de marca, use Content/OnBrandSubtle.',
 'Background/BrandHover': 'Preenchimento de marca sob o mouse.',
 'Content/OnBrandSubtle': 'Texto e ícone de marca sobre Background/BrandSubtle e dentro do anel de foco.',
 'Background/BrandPressed': 'Preenchimento de marca no instante do clique.',
 'Background/BrandSubtle': 'Contêiner claro de marca: chip, faixa, trilho, badge roxo.',
 'Background/BrandSelected': 'Fundo de item ou linha selecionada.',
 # Controle
 'Control/Accent': 'Preenchimento de controle nativo — caixa de marcar, botão de rádio, chave liga/desliga. Nunca é texto.',
 # Conteúdo
 'Content/Primary': 'Título e texto principal sobre fundo claro.',
 'Content/Secondary': 'Subtítulo, texto de apoio e ícone de ação secundária.',
 'Content/Tertiary': 'Texto discreto: instrução, dica, placeholder.',
 'Content/OnFill': 'Conteúdo sobre qualquer preenchimento sólido, e sobre Background/Inverse. Um valor cobre as seis famílias — é o branco puro, o mais legível em todas elas.',
 'Content/Disabled': 'Conteúdo desligado. Isento do mínimo de contraste.',
 # Borda
 'Border/Default': 'Contorno estrutural: campo, card, moldura de tabela.',
 'Border/Moderate': 'Contorno de contêiner clicável que organiza conteúdo, como o acordeão.',
 'Border/Subtle': 'Divisor decorativo: linha de tabela, item de painel, cabeçalho de modal.',
 'Border/Faint': 'Divisor mínimo, dentro de um mesmo bloco.',
 'Border/Hover': 'Contorno de campo sob o mouse, antes de focar.',
 'Border/Strong': 'Contorno escuro de peça pequena sobre fundo claro: o chip de usuário da barra de cima, o botão de ação dentro da tabela. É o degrau mais forte da escala neutra de contorno.',
 'Border/Focus': 'Anel de foco sobre fundo claro.',
 'Border/FocusInner': 'Anel interno do foco, encostado no elemento.',
 'Border/Inverse': 'Borda e anel de foco sobre preenchimento sólido ou fundo escuro.',
 'Border/Brand': 'Contorno de marca: círculo ativo do wizard, chip, traço do indicador de carregamento.',
 'Border/BrandSubtle': 'Contorno de tarja clara de marca — a etiqueta de tipo de cobertura. Um passo mais forte que o preenchimento dela, sem virar contorno de marca cheio.',
 'Border/Disabled': 'Contorno de campo ou controle desligado. Isento do mínimo.',
 'Border/Success': 'Contorno da família sucesso, incluindo o botão de contorno em repouso.',
 'Border/SuccessPressed': 'Contorno do botão de contorno de sucesso no clique.',
 'Border/Danger': 'Contorno da família erro, incluindo a borda do campo com erro.',
 'Border/DangerPressed': 'Contorno do botão de contorno de erro no clique.',
 'Border/Info': 'Contorno da família informação.',
 'Border/Warning': 'Contorno da família alerta.',
 'Border/Risk': 'Contorno da família risco.',
 # Fundo
 'Background/Surface': 'Superfície padrão: card, painel, popover.',
 'Background/Canvas': 'Fundo de página e de área decorativa.',
 'Background/Hover': 'Fundo de lista, linha ou item de árvore sob o mouse. Também é a base do carregamento esqueleto.',
 'Background/Track': 'Trilha vazia: o caminho que a barra de progresso ainda não preencheu, o trilho de um controle.',
 'Background/Neutral': 'Preenchimento neutro sobre a trilha — progresso sem cor de estado, etapa já concluída de um passo a passo. Em cima dele vai Content/OnFill.',
 'Background/Inverse': 'Fundo escuro com conteúdo claro em cima: dica flutuante, faixa escura.',
 # Sucesso
 'Background/SuccessVivid': 'Só decoração: faixa, ilustração, gráfico. Nunca carrega texto nem ícone.',
 'Background/Success': 'Preenchimento de sucesso, como o botão de aprovar.',
 'Content/Success': 'Texto e ícone de sucesso, sobre fundo claro neutro e sobre Background/SuccessSubtle.',
 'Content/OnSuccessSubtle': 'Texto e ícone sobre Background/SuccessSubtle.',
 'Background/SuccessHover': 'Preenchimento de sucesso sob o mouse. Também é a cor de texto do botão de contorno de sucesso.',
 'Background/SuccessPressed': 'Preenchimento de sucesso no clique.',
 'Background/SuccessSubtle': 'Contêiner claro de sucesso: etiqueta, chip, faixa.',
 'Background/SuccessSubtleHover': 'Botão de contorno de sucesso sob o mouse.',
 'Background/SuccessSubtlePressed': 'Botão de contorno de sucesso no clique.',
 'Content/OnSuccessSubtlePressed': 'Texto do botão de contorno de sucesso no clique.',
 # Perigo
 'Content/Danger': 'Texto e ícone de erro sobre fundo claro neutro: asterisco de campo obrigatório, mensagem de erro.',
 'Background/Danger': 'Preenchimento de erro, como o botão de excluir.',
 'Content/OnDangerSubtle': 'Texto e ícone sobre Background/DangerSubtle.',
 'Background/DangerHover': 'Preenchimento de erro sob o mouse.',
 'Background/DangerPressed': 'Preenchimento de erro no clique.',
 'Content/OnDangerSubtlePressed': 'Texto do botão de contorno de erro no clique.',
 'Background/DangerSubtle': 'Contêiner claro de erro: etiqueta, chip. Também é o fundo do botão de contorno de erro sob o mouse.',
 'Background/DangerSubtlePressed': 'Botão de contorno de erro no clique.',
 # Alerta
 'Background/WarningVivid': 'Só decoração. Nunca carrega texto nem ícone.',
 'Background/Warning': 'Preenchimento de alerta. Mesmo valor do Content/Warning, em papel de fundo.',
 'Background/WarningHover': 'Preenchimento de alerta sob o mouse.',
 'Background/WarningPressed': 'Preenchimento de alerta no clique.',
 'Content/Warning': 'Texto e ícone de alerta, sobre fundo claro neutro e sobre Background/WarningSubtle.',
 'Content/OnWarningSubtle': 'Texto e ícone sobre Background/WarningSubtle.',
 'Background/WarningSubtle': 'Contêiner claro de alerta: etiqueta, chip, faixa.',
 # Risco
 'Background/RiskVivid': 'Só decoração. Nunca carrega texto nem ícone.',
 'Background/Risk': 'Preenchimento de risco. Mesmo valor do Content/Risk, em papel de fundo.',
 'Background/RiskHover': 'Preenchimento de risco sob o mouse.',
 'Background/RiskPressed': 'Preenchimento de risco no clique.',
 'Content/Risk': 'Texto e ícone de risco, sobre fundo claro neutro e sobre Background/RiskSubtle.',
 'Content/OnRiskSubtle': 'Texto e ícone sobre Background/RiskSubtle.',
 'Background/RiskSubtle': 'Contêiner claro de risco: etiqueta, chip, faixa.',
 # Informação
 'Content/InfoLarge': 'Apenas ícone ou texto grande, de 24px para cima.',
 'Background/Info': 'Preenchimento de informação. Mesmo valor do Content/Info, em papel de fundo.',
 'Background/InfoHover': 'Preenchimento de informação sob o mouse.',
 'Background/InfoPressed': 'Preenchimento de informação no clique.',
 'Content/Info': 'Texto e ícone de informação, sobre fundo claro neutro e sobre Background/InfoSubtle.',
 'Content/OnInfoSubtle': 'Texto e ícone sobre Background/InfoSubtle.',
 'Background/InfoSubtle': 'Contêiner claro de informação: etiqueta, chip, faixa.',
 # Sobreposição
 'Overlay/Scrim': 'Escurecimento atrás de qualquer janela modal — um único valor para toda a plataforma. Nunca recebe conteúdo em cima.',
}
